### ISSUE TITLE
Won't run on Android

### ISSUE THREAD

**Issue by FossPrime** [mrwnwttk/audius-dl#4]
```
/data/data/com.termux/files/usr/lib/python3.10/site-packages/joblib/_multiprocessing_helpers.py:45: UserWarning: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.10/lib-dynload/_multiprocessing.cpython-310.so).  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.10/lib-dynload/_multiprocessing.cpython-310.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/third-party/audius-dl/audius-dl.py", line 12, in <module>
    from joblib import Parallel, delayed
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/joblib/parallel.py", line 30, in <module>
    from .externals import loky
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/joblib/externals/loky/__init__.py", line 11, in <module>
    from .backend.context import cpu_count
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/joblib/externals/loky/backend/__init__.py", line 13, in <module>
    from multiprocessing import synchronize
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
~ $
```

Using the latest Termux from F-Droid on Android 12. Ultimately I'd like to use the widget to read my clipboard and move it to my Music Automagically

**Comment by mrwnwttk** [comment]
Out of my control, see https://github.com/termux/termux-app/issues/1272. Android lacks support for semaphores. A workaround for this would be to skip the import of joblib and handle downloading the segments without parallelism, but that's really just a bandaid fix, which would slow things down significantly.
