### ISSUE TITLE
Does not work 2023 on Windows

### ISSUE THREAD

**Issue by AnonA2** [mrwnwttk/audius-dl#7]
D:\Tag_X all\10.7.23\Programs\audius.co downloader - with visuals and search par
ameter and track title and image\audius-dl-master\audius-dl-master>python audius
-dl.py https://audius.co/sumreets10
API endpoint: https://discoveryprovider2.audius.co
Total number of tracks: 53
Found 53 track(s)!
Track [ 1 / 53 ]
API endpoint: https://audius-discovery-13.cultur3stake.com
Node endpoints: https://creatornode3.audius.co / https://audius-content-2.cultur
3stake.com / https://audius-content-2.figment.io
Selected node endpoint: https://creatornode3.audius.co
Number of segments: 0

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mutagen\_util.py", line 250, in _openfile

    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'KplJOqy.m4a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Tag_X all\10.7.23\Programs\audius.co downloader - with visuals and se
arch parameter and track title and image\audius-dl-master\audius-dl-master\audiu
s-dl.py", line 472, in <module>
    main()
  File "D:\Tag_X all\10.7.23\Programs\audius.co downloader - with visuals and se
arch parameter and track title and image\audius-dl-master\audius-dl-master\audiu
s-dl.py", line 461, in main
    download_profile(link)
  File "D:\Tag_X all\10.7.23\Programs\audius.co downloader - with visuals and se
arch parameter and track title and image\audius-dl-master\audius-dl-master\audiu
s-dl.py", line 409, in download_profile
    download_single_track_from_api(i, username)
  File "D:\Tag_X all\10.7.23\Programs\audius.co downloader - with visuals and se
arch parameter and track title and image\audius-dl-master\audius-dl-master\audiu
s-dl.py", line 285, in download_single_track_from_api
    add_tags(track_id, data['data']['title'], data['data']['user']['name'], desc
ription, cover)
  File "D:\Tag_X all\10.7.23\Programs\audius.co downloader - with visuals and se
arch parameter and track title and image\audius-dl-master\audius-dl-master\audiu
s-dl.py", line 27, in add_tags
    tags = MP4(filename + ".m4a").tags
  File "C:\Python310\lib\site-packages\mutagen\_file.py", line 47, in __init__
    self.load(*args, **kwargs)
  File "C:\Python310\lib\site-packages\mutagen\_util.py", line 153, in wrapper
    with _openfile(self, filething, filename, fileobj,
  File "C:\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Python310\lib\site-packages\mutagen\_util.py", line 271, in _openfile

    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'KplJOqy.m4a'

D:\Tag_X all\10.7.23\Programs\audius.co downloader - with visuals and search par
ameter and track title and image\audius-dl-master\audius-dl-master>

**Comment by mrwnwttk** [comment]
Took a quick look a what was changed on the backend. Turns out they now want you to provide a signature for whatever node endpoint you're using. I'll be honest, I have no intention of implementing that. 

As it stands right now I'm perfectly fine just letting this tool sit here in its broken state. I'll archive the repo and if someone else wants to fix it, they can fork it.
